apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: tools
  storageNamespace: tools
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "v6.14.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    - provider: azure
      logLevel: debug
      txtOnwnerId: external-dns
      azure:
        useManagedIdentityExtension: true
        tenantId: 5cc80b30-6dfd-4dc3-bbce-aca1faf46c4d
        subscriptionId: b4172030-9800-43dc-947c-05426b39e4d2
        resourceGroup: cluster-rg
      domainFilters:
        - danielscholl.info
