apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  targetNamespace: tools
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
      version: "v7.0.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
