apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  targetNamespace: tools
  releaseName: reflector
  chart:
    spec:
      chart: emberstack/reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      version: v7.0.151
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
