apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configuration
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: components
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./configuration
  prune: true