---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  targetNamespace: istio-system
  releaseName: kiali-operator
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: "1.64.0"
  interval: 1h0m0s
  values:
    cr:
      create: true
      name: kiali
      namespace: "istio-system"
